
# Set default values for cartridge dependency
cartridge:
  ClusterEnv: dev
  ClusterName: crud-app

  image:
    repository: tarantool/crud-app
    tag: 0.1.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8081

  Prometheus:
    port: 8081
    path: /metrics

  RoleConfig:
    - RoleName: crud
      ReplicaCount: 2
      ReplicaSetCount: 2
      DiskSize: 1Gi
      CPUallocation: 0.25
      MemtxMemoryMB: 256
      RolesToAssign:
        - crud-storage
        - crud-router
        - migrator
        - metrics
