# permissions for end users to view cartridgeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cartridgeconfig-viewer-role
rules:
- apiGroups:
  - tarantool.io
  resources:
  - cartridgeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tarantool.io
  resources:
  - cartridgeconfigs/status
  verbs:
  - get
