# fixme: workaround for https://github.com/kubernetes-sigs/controller-tools/issues/752
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/ephemeralContainers/items/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
   - name
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/ephemeralContainers/items/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/containers/items/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/containers/items/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/initContainers/items/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/initContainers/items/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/volumes/items/properties/ephemeral/properties/volumeClaimTemplate/properties/spec/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/template/properties/spec/properties/volumes/items/properties/ephemeral/properties/volumeClaimTemplate/properties/spec/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/volumeClaimTemplates/items/properties/spec/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/storageTemplate/properties/spec/properties/volumeClaimTemplates/items/properties/spec/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/volumeClaimTemplates/items/properties/spec/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/volumeClaimTemplates/items/properties/spec/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/containers/items/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/containers/items/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/ephemeralContainers/items/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/ephemeralContainers/items/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/volumes/items/properties/ephemeral/properties/volumeClaimTemplate/properties/spec/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/volumes/items/properties/ephemeral/properties/volumeClaimTemplate/properties/spec/properties/resources/properties/claims/x-kubernetes-list-type
  value: map

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/initContainers/items/properties/resources/properties/claims/x-kubernetes-list-map-keys
  value:
    - name
- op: replace
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/replicasetTemplate/properties/podTemplate/properties/spec/properties/initContainers/items/properties/resources/properties/claims/x-kubernetes-list-type
  value: map
