---
# Here you can specify default parameters for local running, such as:

# cfg: path-to-cfg-file
# log-dir: path-to-log-dir
# run-dir: path-to-run-dir
# data-dir: path-to-data-dir

stateboard: false # If no arguments are supplied, --stateboard flag is true
