name: Run unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go 1.19.3
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: Test
        run: go test ./... -coverprofile cover.out