name: Test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      OPERATOR_SDK_VERSION: v0.12.0
    steps:

    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install modules
      run: go mod download

    - name: Install operator-sdk
      run: |
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu
        chmod +x ./operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu

    - name: Build operator
      run: ./operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu build tarantool/tarantool-operator:${GITHUB_SHA}

    - name: Setup test kubernetes cluster
      uses: helm/kind-action@v1.0.0-rc.1
      with:
        cluster_name: kind

    - name: Load operator image into test cluster
      run: kind load docker-image tarantool/tarantool-operator:${GITHUB_SHA}

    - name: Create CRDs
      run: |
        kubectl create \
          -f deploy/crds/tarantool_v1alpha1_cluster_crd.yaml \
          -f deploy/crds/tarantool_v1alpha1_replicasettemplate_crd.yaml \
          -f deploy/crds/tarantool_v1alpha1_role_crd.yaml

    - name: Test
      run: |
        ./operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu test local \
          --image tarantool/tarantool-operator:${GITHUB_SHA} \
          ./test/e2e
