name: Test

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - uses: actions/checkout@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v --timeout 2m --config .golangci.yml
          version: v1.50.1

  test:
    name: unit testing
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Test
        run: go test ./... -coverprofile cover.out